Add file with SQL code required for Practice 3.8
AndreyPanda/DBP_SQL pull request #1
Opened 2023-03-12 12:09 UTC by AndreyPanda

2023-03-13 09:48 UTC, aleksandr-semenov-dbp requested changes

2023-03-13 09:48 UTC, aleksandr-semenov-dbp commented on SQL code for tables creation and queries.md
> +SELECT MIN (salary) FROM employees WHERE department_id = 2;
Здесь надо одним запросом получить таблицу департамент(имя) | минимальная зарплата | максимальная зарплата

2023-03-14 07:26 UTC, AndreyPanda commented on SQL code for tables creation and queries.md
> +SELECT MIN (salary) FROM employees WHERE department_id = 2;
Принято, обновлю, создам новый PR.

2023-03-14 09:08 UTC, closed without merging

2023-03-14 09:09 UTC, AndreyPanda commented
One query to be updated. A new PR will be created.